print('What is your name?')
myName = input()
print ("")
print('Well, ' +  myName  +  ' , I have some jokes for you ' )

print('What do you get when you cross a snowman with a Vampire?')
input()
print('Frostbite!')
print()
print('What do dentists call a astronaut\'s cavity?')
input()
print('A black hole!')
print()
print('Knock knock.')
input()
print("Who's there?")
input()
print('Interrupting cow.')
input()
print('Interupting cow we', end='')
print('-MOO!')
print()
print(myName  +  ' , thats all I have for you!  ' )
